# Generated by Django 5.1.3 on 2025-02-22 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='reference',
            field=models.TextField(default=''),
        ),
    ]
