# Generated by Django 5.1.3 on 2025-02-23 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_message_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='session_key',
            field=models.CharField(default='NONE', max_length=32),
        ),
    ]
